   
security:
  basic:
    enabled: false
  ignored: /**
  
management:
  security:
    enabled: false
        
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
###
# Logging levels - local dev debug.
###
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.type: DEBUG
    org.flywaydb.core.internal.dbsupport.SqlScript: DEBUG
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
        
