server:
  port: 8015
   
###
# Flyway script location - local enviroment in memory h2 DB.
###
flyway:
  locations: classpath:db/h2

security:
  basic:
    enabled: false
  ignored: /**
  
management:
  security:
    enabled: false
        
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    

###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:h2:file:~/companytest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false      

###
# Logging levels - local dev debug.
###
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.type: DEBUG
    org.flywaydb.core.internal.dbsupport.SqlScript: DEBUG
    org.flywaydb: DEBUG
    org.springframework.security: DEBUG
        
